name: Remember new templates and update CONTEXT

on:
  push:
    branches: [ "main" ]
    paths:
      - 'TotalNews*.py'
      - 'templates/**'
      - 'sessions/aliases.md'
      - '.remember/**'
      - 'sessions/*.remember'
      - 'sessions/*.md'

permissions:
  contents: write

jobs:
  update-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run context updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python3 scripts/update_context.py
          
